spring.security.user:
  name: ${BASIC_AUTH_SECURITY_USER:davide}
  password: ${BASIC_AUTH_SECURITY_PASSWORD:davide}

spring.data.mongodb:
  uri: mongodb://${MONGO_USER:}:${MONGO_PASSWORD:}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${MONGO_NAME:test}